# Generated by Django 2.2.24 on 2023-09-09 10:24

from django.db import migrations


def fill_field_new_building(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    Flats.objects.filter(construction_year__gt=2014).update(new_building=True)
    Flats.objects.exclude(construction_year__gt=2014).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_field_new_building)
    ]
