# Generated by Django 2.2.24 on 2023-09-09 10:24

from django.db import migrations


def fill_field_new_building(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    for flat in Flats.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
        elif flat.construction_year < 2015:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_field_new_building)
    ]
