# Generated by Django 2.2.24 on 2023-09-16 10:19

from django.db import migrations
import phonenumbers


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.iterator():
        if flat.owners_phonenumber:
            try:
                owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
                if phonenumbers.is_valid_number(owner_pure_phone):
                    flat.owner_pure_phone = owner_pure_phone
                    flat.save()
            except phonenumbers.phonenumberutil.NumberParseException:
                pass
            


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number)
    ]
