# Generated by Django 2.2.24 on 2023-10-07 09:18

from django.db import migrations
from property.models import Flat, Owner


def copy_owners_from_flat_model(apps, schema_editor):
    for flat in Flat.objects.iterator():
        owner, created = Owner.objects.get_or_create(name=flat.owner, pure_phone=flat.owner_pure_phone)
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230916_1404'),
    ]

    operations = [
        migrations.RunPython(copy_owners_from_flat_model)
    ]
